export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";

export const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAILURE = "USER_SIGN_UP_FAILURE";

export const CHECK_EMAIL_REQUEST = " CHECK_EMAIL_REQUEST";
export const CHECK_EMAIL_SUCCESS = " CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_FAILURE = " CHECK_EMAIL_FAILURE";

export const MODAL_OPEN_REQUEST = "MODAL_OPEN_REQUEST";
export const MODAL_CLOSE_REQUEST = "MODAL_CLOSE_REQUEST";

export const SWITCH_LANGUAGE_TYPE = "SWITCH_LANGUAGE_TYPE";

export const GET_USER_ARTICLE_REQUEST = "GET_USER_ARTICLE_REQUEST";
export const GET_USER_ARTICLE_SUCCESS = "GET_USER_ARTICLE_SUCCESS";
export const GET_USER_ARTICLE_FAILURE = "GET_USER_ARTICLE_FAILURE";